### ISSUE TITLE
Scroll school fixes

### ISSUE THREAD

**Issue by Grammarsalad** [RedChimera/semiOverhaul-v1.32#4]
We should patch these

**Comment by semiticgod** [comment]
I believe there are two different parts of the code that deal with spell scroll schools: one that copies them to get the usability flags right, and then another section that patches them to give them the right descriptions. I've actually had trouble in dealing with patching flags because they seem to be multiple byte fields and I'm not sure whether to use WRITE_BYTE with multiple offsets or WRITE_SHORT or WRITE_LONG to try to write over multiple bytes in sequence.

If we switch to simply patching both flags and descriptions, we should bear in mind that this won't fix Halt Undead and Animate Dead. The vanilla Halt Undead scroll has faulty usability flags (and some other scrolls might, too) and would not be noticed by the patch commands, so we'd have to patch it by name instead of by READing the flags. Animate Dead must be rigged to grant both Animate Skeleton and Animate Zombie unless we replace the scroll with two different scrolls. That would require adding the new scroll to stores.

Note that scrolls for new spells such as Spook would have to be copied instead of patched. I think all of these scrolls have the prefix USWI or USSPWI instead instead of SPWI.

**Comment by Grammarsalad** [comment]
Usability is better using bitwise operators: http://www.weidu.org/~thebigg/README-WeiDU.html#sec31

It probably works slightly differently in IWD2 than in vanilla (and EE), but this is the place to start.  I can help with this after reorganization.

**Comment by OlvynChuru** [comment]
Bubb13 has fixed these problems. All the spells now abide by the new specialist restrictions, without requiring the spell to be cast through the scroll to learn it.
